---
- hosts: all
  name: Include OS
  gather_facts: true
  become: true
  tasks:
  - name: Performing Tasks for CentOS
    include_tasks: ./vars/RedHat.yml
    when: ansible_facts['distribution'] == 'CentOS'


  - name: Performing Tasks for Ubuntu
    include_tasks: ./vars/Debian.yml
    when: ansible_facts['distribution'] == 'Ubuntu'

  
    

