---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: Ubuntu
    image: ami-0d03e44a2333dea65
    instance_type: t2.micro
    vpc_subnet_id: subnet-0ec26b5bcbc752011
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../../playbook.yml
    prepare: ../default/prepare.yml
verifier:
  name: testinfra
  lint:
    name: flake8
